### ISSUE TITLE
Determine LULC pixel counts for catchment and for flood extent

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [BradfordBates-NOAA/catchment-enricher#8]
Basic requirements as of now:

- [ ] Write script with function to determine LULC pixel counts for any given polygon (#7)
- [ ] Test tool from on a single HUC8, using catchments layer provided by Brad
- [ ] Use tool at the entire NWM modeling domain (all HUCs and catchments)
- [ ] Use tool to determine relevant pixel counts for catchments given a specific recurrence flow inundation extent

Sample catchment geopackage and tiff [here](https://drive.google.com/drive/folders/1QKI1qDMp4q0sPb7KgNixFj3yYeSYuvor?usp=sharing). Sample inundation maps are also available here.

More requirements to follow.

**Comment by BradfordBates-NOAA** [comment]
@fastnish @sophiecress Please note that I added a link to sample catchment data in this issue's description.

**Comment by fastnish** [comment]
Hey guys- I did a quick validation on ArcPro for 2 LC classes and it looks like our script is working correctly. So... yay!

**Comment by sophiecress** [comment]
Awesome-I also ran it on Wednesday and it worked for me too. I love seeing the table populate!
